---
# Nginx

- name: check file information
  #shell: grep "{{ fcont }}" {{ myfname }} /dev/null
  shell: echo "$PATH"
  register: raw_result

- name: stdout of file info.
  debug: var=raw_result.stdout_lines

#- name: do rake -AT
#  shell: rake -AT
  
- name: do serverspec
  shell: /tmp/RUNRUN
  #shell: PATH="/home/hmizuno/.rbenv/bin:$PATH" /home/hmizuno/.rbenv/shims/rake serverspec:CHECK
  #shell: SUDO_PASSWORD=Hiromizuno1-- /home/hmizuno/.rbenv/shims/rake serverspec:CHECK
  register: raw_result

- name: stdout of serverspec
  debug: var=raw_result.stdout_lines
